### ISSUE TITLE
Max Position error

### ISSUE THREAD

**Issue by Dave00896** [AtsutaneDotNet/LickHunterPro-Assistant#1]
Hi would like to inquire whether I am the only one experiencing this issue. When starting the bot the bot automatically changes the max position value to zero no matter how many times I have tried to change it and restart the bot.

**Comment by AtsutaneDotNet** [comment]
Probably high percent bal value. The calculation is like this. Percent bal / 100 = total position. Total position / MaxPerPos = Auto MaxPosition value.
