### ISSUE TITLE
Multiple timeframe for long offset and short offset

### ISSUE THREAD

**Issue by wormsound** [AtsutaneDotNet/LickHunterPro-Assistant#2]
Ref: https://liquidation.atsutane.net/research
Both Long and Short offset% are based on 1H TF. Am I correct? How about if I trade on lower timeframe like 15 minutes? If it possible to how long and short offset% for 15 minites?

**Comment by AtsutaneDotNet** [comment]
According to CCXT documentation https://ccxt.readthedocs.io/en/latest/manual.html#ticker-structure the vwap is calculated base on the past 24 hours data.

After checking on TV using https://www.tradingview.com/script/t2Gtklsp-LHP-1hr-VWAP-Offset-by-Johnny-Cucuzza/ it's should be similar regardless of TF use.
