### ISSUE TITLE
Multiple websockets open after a period of time

### ISSUE THREAD

**Issue by imqct** [AtsutaneDotNet/LickHunterPro-Assistant#3]
After running the Assistant for a day, you can see that multiple Websockets will be opened.

![image](https://user-images.githubusercontent.com/4360673/136306121-157731a7-040a-498d-9ac4-d6defa8fcafc.png)

**Comment by AtsutaneDotNet** [comment]
Can't seem to replicate this on 3 of my VPS. All running without any problem for the past 4 days.

It's a known issue even before LHA being built - https://discord.com/channels/378283630360789003/685258964266647564/809702035595198485
